## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

### 1.1 (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Obtendo o número de acertos
np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

# Nome das colunas
notas_columns = [
    "df_mat",
    "df_por",
    "df_geo",
    "df_ing",
    "df_his",
    "df_fis",
    "df_qui",
]

# Instanciando uma DataFrame com todos os acertos
df_notas = pd.concat([df_mat, df_por, df_geo, df_ing, df_his, df_fis, df_qui], axis=1)
df_notas.columns = notas_columns
df_notas.head()

   df_mat  df_por  df_geo  df_ing  df_his  df_fis  df_qui
0       6       7       7       3       1       8       3
1      19      10       0       0       0      11       8
2      14      16       0       5       7       4       4
3      10       7       3       4       0       0       8
4       7       2       2       7       0       9       3

In [3]:
# 1) Seu código aqui

# Instanciando com o número de questões de cada matéria
assunto	= [
    "Matemática",
    "Português",
    "Geografia",
    "Inglês",
    "História",
    "Física",
    "Química",
]

numero_questoes = [
    24,
    18,
    8,
    8,
    8,
    12,
    12,
]

codigo	= [
    "df_mat",
    "df_por",
    "df_geo",
    "df_ing",
    "df_his",
    "df_fis",
    "df_qui",
]
numero_questoes = pd.DataFrame(columns=["assunto","número de questões","código"], data=zip(assunto, numero_questoes, codigo))
numero_questoes

      assunto  número de questões  código
0  Matemática                  24  df_mat
1   Português                  18  df_por
2   Geografia                   8  df_geo
3      Inglês                   8  df_ing
4    História                   8  df_his
5      Física                  12  df_fis
6     Química                  12  df_qui

In [4]:
# Calcula a porcentagem para cada uma das colunas da DataFrame com os acertos.
coluna = 0
while coluna < len(numero_questoes):

  # Obtem o nome da nova coluna, com base no nome da coluna calculada
  nome_coluna = numero_questoes.iloc[coluna,2] + "_porc"

  # Obtem a porcentagem, dividindo o número de acertos pelo total de questões, multiplicando por 100.
  valor = round((df_notas.iloc[:,coluna] / numero_questoes.iloc[coluna,1])*100, 2)

  # Insere as porcentagens na DataFrame com as notas
  df_notas[nome_coluna] = valor

  # Soma para ser utilizada como index
  coluna += 1
df_notas.head()

,df_mat,df_por,df_geo,df_ing,df_his,df_fis,df_qui,df_mat_porc,df_por_porc,df_geo_porc,df_ing_porc,df_his_porc,df_fis_porc,df_qui_porc
0,6,7,7,3,1,8,3,25.00,38.89,87.5,37.5,12.5,66.67,25.00
1,19,10,0,0,0,11,8,79.17,55.56,0.0,0.0,0.0,91.67,66.67
2,14,16,0,5,7,4,4,58.33,88.89,0.0,62.5,87.5,33.33,33.33
3,10,7,3,4,0,0,8,41.67,38.89,37.5,50.0,0.0,0.00,66.67
4,7,2,2,7,0,9,3,29.17,11.11,25.0,87.5,0.0,75.00,25.00

In [5]:
# Para organizar a DataFrame com as notas, no formato acerto, porcentagem

# Obtem uma lista com a primeira metade ds primeiros index de colunas
freq_abso = [i for i in range(int(len(df_notas.columns)/2))]

# Obtem uma lista com a segunda metade ds primeiros index de colunas
freq_rela = [j for j in range(int(len(df_notas.columns)/2), len(df_notas.columns))]

# Concatena as listas
n_colunas = freq_abso + freq_rela

# Intercala as listas
n_colunas[::2] = freq_abso
n_colunas[1::2] = freq_rela

n_colunas

[0, 7, 1, 8, 2, 9, 3, 10, 4, 11, 5, 12, 6, 13]

In [6]:
# Usa a lista com os index intercalados para reorganizar a DataFrame
df_notas = df_notas[df_notas.columns[n_colunas]]
df_notas.head()

,df_mat,df_mat_porc,df_por,df_por_porc,df_geo,df_geo_porc,df_ing,df_ing_porc,df_his,df_his_porc,df_fis,df_fis_porc,df_qui,df_qui_porc
0,6,25.00,7,38.89,7,87.5,3,37.5,1,12.5,8,66.67,3,25.00
1,19,79.17,10,55.56,0,0.0,0,0.0,0,0.0,11,91.67,8,66.67
2,14,58.33,16,88.89,0,0.0,5,62.5,7,87.5,4,33.33,4,33.33
3,10,41.67,7,38.89,3,37.5,4,50.0,0,0.0,0,0.00,8,66.67
4,7,29.17,2,11.11,2,25.0,7,87.5,0,0.0,9,75.00,3,25.00

### 1.2 (operações entre *DataFrames) Calcule o total de acertos de cada aluno.

In [7]:
# 2) Seu código aqui

# O total de acertos é somado para cada aluno, inserindo o dado na DataFrame
df_notas['soma_acertos'] = df_notas.select_dtypes("int64").T.sum()
df_notas.head()

,df_mat,df_mat_porc,df_por,df_por_porc,df_geo,df_geo_porc,df_ing,df_ing_porc,df_his,df_his_porc,df_fis,df_fis_porc,df_qui,df_qui_porc,soma_acertos
0,6,25.00,7,38.89,7,87.5,3,37.5,1,12.5,8,66.67,3,25.00,35
1,19,79.17,10,55.56,0,0.0,0,0.0,0,0.0,11,91.67,8,66.67,48
2,14,58.33,16,88.89,0,0.0,5,62.5,7,87.5,4,33.33,4,33.33,50
3,10,41.67,7,38.89,3,37.5,4,50.0,0,0.0,0,0.00,8,66.67,32
4,7,29.17,2,11.11,2,25.0,7,87.5,0,0.0,9,75.00,3,25.00,30

### 1.3 Calcule o porcentual geral de cada aluno.

In [8]:
# 3) Seu código aqui

# O total de acertos (última coluna) é dividido pelo totral de questões, e inserido no final da data
df_notas['porc_geral'] = round((df_notas['soma_acertos'] / numero_questoes['número de questões'].sum())*100, 2)
df_notas.head()

,df_mat,df_mat_porc,df_por,df_por_porc,df_geo,df_geo_porc,df_ing,df_ing_porc,df_his,df_his_porc,df_fis,df_fis_porc,df_qui,df_qui_porc,soma_acertos,porc_geral
0,6,25.00,7,38.89,7,87.5,3,37.5,1,12.5,8,66.67,3,25.00,35,38.89
1,19,79.17,10,55.56,0,0.0,0,0.0,0,0.0,11,91.67,8,66.67,48,53.33
2,14,58.33,16,88.89,0,0.0,5,62.5,7,87.5,4,33.33,4,33.33,50,55.56
3,10,41.67,7,38.89,3,37.5,4,50.0,0,0.0,0,0.00,8,66.67,32,35.56
4,7,29.17,2,11.11,2,25.0,7,87.5,0,0.0,9,75.00,3,25.00,30,33.33

### 1.4 Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [9]:
# 4) Seu código aqui

# Filtra apenas alunos com porcentagem de acertos superior ou igual a 45
print(f"{(df_notas['porc_geral'] >= 45).sum()} alunos foram aprovados")

47 alunos foram aprovados



---

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

### 2.1 Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.

In [10]:
# seu código aqui
# São obtidos os alunos com nehhum acerto em física ou matemática ou química
df_notas_desclass = df_notas[
                      (df_notas['df_mat'] == 0) |
                      (df_notas['df_fis'] == 0) |
                      (df_notas['df_qui'] == 0)
]
df_notas_desclass.head()

,df_mat,df_mat_porc,df_por,df_por_porc,df_geo,df_geo_porc,df_ing,df_ing_porc,df_his,df_his_porc,df_fis,df_fis_porc,df_qui,df_qui_porc,soma_acertos,porc_geral
3,10,41.67,7,38.89,3,37.5,4,50.0,0,0.0,0,0.00,8,66.67,32,35.56
6,6,25.00,0,0.00,7,87.5,7,87.5,5,62.5,0,0.00,4,33.33,29,32.22
10,10,41.67,8,44.44,3,37.5,2,25.0,1,12.5,7,58.33,0,0.00,31,34.44
12,20,83.33,8,44.44,3,37.5,7,87.5,1,12.5,0,0.00,3,25.00,42,46.67
14,7,29.17,11,61.11,1,12.5,7,87.5,1,12.5,4,33.33,0,0.00,31,34.44

### 2.2 Quantos são esses alunos?

In [11]:
# Obtem o número de alunos da DataFrame de desclassificados
print(f"São {len(df_notas_desclass)} alunos com nehhum acerto em física ou matemática ou química!")

São 23 alunos com nehhum acerto em física ou matemática ou química!

### 2.3 Qual a média desses alunos em história e geografia?

In [12]:
# Obtem a média das notas de hsitória e geografia de todos os alunos desclassificados
media_his, media_geo = df_notas_desclass[['df_his_porc',"df_geo_porc"]].mean().values.round(2)
print(f"Esses alunos têm média de {media_his}% em história e {media_geo}% em geografia")

Esses alunos têm média de 42.93% em história e 40.22% em geografia

### 2.4 Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [13]:
# Seleciona todos os alunos que não zeraram em matemática e física e química
df_notas_class = df_notas[
                  (df_notas['df_mat'] != 0) &
                  (df_notas['df_fis'] != 0) &
                  (df_notas['df_qui'] != 0)
]
df_notas_class.head()

,df_mat,df_mat_porc,df_por,df_por_porc,df_geo,df_geo_porc,df_ing,df_ing_porc,df_his,df_his_porc,df_fis,df_fis_porc,df_qui,df_qui_porc,soma_acertos,porc_geral
0,6,25.00,7,38.89,7,87.5,3,37.5,1,12.5,8,66.67,3,25.00,35,38.89
1,19,79.17,10,55.56,0,0.0,0,0.0,0,0.0,11,91.67,8,66.67,48,53.33
2,14,58.33,16,88.89,0,0.0,5,62.5,7,87.5,4,33.33,4,33.33,50,55.56
4,7,29.17,2,11.11,2,25.0,7,87.5,0,0.0,9,75.00,3,25.00,30,33.33
5,20,83.33,2,11.11,5,62.5,3,37.5,2,25.0,9,75.00,9,75.00,50,55.56

In [14]:
# Verifica se todos os alunos soram selecionados
len(df_notas_class) + len(df_notas_desclass) == len(df_notas)

True



---

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [15]:
# Importa os dados do site do Minstério da Saúde, usando um novo link
# arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'
arquivo =   "https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-97829158-cc41-4c75-aec4-752344e6e938.c000.csv"
df_vacinas = pd.read_csv(arquivo, sep=";")
df_vacinas.head()

<ipython-input-15-320f6e16a317>:4: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vacinas = pd.read_csv(arquivo, sep=";")

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,a7b2e803-75ae-4c59-baa7-421d87f9a707-i0b0,3e35925a3512d7901cd2974eb662e25b6130ee42e72317...,30,1991-08-30,F,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,205F21A,JANSSEN,Organization/30587,2022-05-26,Reforço,88,COVID-19 JANSSEN - Ad26.COV2.S,Novo PNI
1,5ec41855-c5b8-44de-88d0-a474814e9df0-i0b0,ac91ba1d57f1ec0a8c88e393ed7e162914cecaa47d8624...,38,1982-09-20,F,2,PRETA,120020.0,10.0,CRUZEIRO DO SUL,...,2.0,Faixa Etária,214VCD053W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-07-02,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
2,c5b89122-8166-4f7e-9ef3-1a98c8e65d52-i0b0,578eff022445b36a42ef61a011ec5517523a563c5321a7...,20,2001-03-21,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-10-25,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
3,5ef90995-413a-44df-bfb2-64dec20fc20f-i0b0,6991fbfb4e56ef4193b09f7a6203604356b3c3b739101e...,30,1990-12-07,M,4,AMARELA,120050.0,10.0,SENA MADUREIRA,...,2.0,Faixa Etária,214VCD053W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-08-03,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
4,7177c695-3e14-42fd-8a7c-ef76ebe92360-i0b0,b1ead8d542ffb8e8f387426cb6e134d39979759c1ae190...,63,1957-06-09,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,210135,SINOVAC/BUTANTAN,Organization/61189445000156,2021-05-10,2ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI

In [16]:
# Filtra para apenas vacinas administradas na capital do Acre, Rio Branco
df_vacinas_acre = df_vacinas[df_vacinas['paciente_endereco_nmMunicipio'] == "RIO BRANCO"].copy()
df_vacinas_acre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 182451 entries, 0 to 375520
Data columns (total 32 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   document_id                               182451 non-null  object
 1   paciente_id                               182451 non-null  object
 2   paciente_idade                            182451 non-null  int64
 3   paciente_dataNascimento                   182451 non-null  object
 4   paciente_enumSexoBiologico                182451 non-null  object
 5   paciente_racaCor_codigo                   182451 non-null  int64
 6   paciente_racaCor_valor                    182451 non-null  object
 7   paciente_endereco_coIbgeMunicipio         182451 non-null  object
 8   paciente_endereco_coPais                  182451 non-null  object
 9   paciente_endereco_nmMunicipio             182451 non-null  object
 10  paciente_endereco_nmPais                  182451 non-null  object
 11  paciente_endereco_uf                      182451 non-null  object
 12  paciente_endereco_cep                     156987 non-null  object
 13  paciente_nacionalidade_enumNacionalidade  182396 non-null  object
 14  estabelecimento_valor                     182451 non-null  int64
 15  estabelecimento_razaoSocial               182451 non-null  object
 16  estalecimento_noFantasia                  182451 non-null  object
 17  estabelecimento_municipio_codigo          182451 non-null  int64
 18  estabelecimento_municipio_nome            182451 non-null  object
 19  estabelecimento_uf                        182451 non-null  object
 20  vacina_grupoAtendimento_codigo            182451 non-null  int64
 21  vacina_grupoAtendimento_nome              181984 non-null  object
 22  vacina_categoria_codigo                   174002 non-null  float64
 23  vacina_categoria_nome                     174002 non-null  object
 24  vacina_lote                               182451 non-null  object
 25  vacina_fabricante_nome                    182451 non-null  object
 26  vacina_fabricante_referencia              182146 non-null  object
 27  vacina_dataAplicacao                      182451 non-null  object
 28  vacina_descricao_dose                     182451 non-null  object
 29  vacina_codigo                             182451 non-null  int64
 30  vacina_nome                               182449 non-null  object
 31  sistema_origem                            182410 non-null  object
dtypes: float64(1), int64(6), object(25)
memory usage: 45.9+ MB

### 3.1 Quantas vacinas estão registradas nessa base?

In [17]:
def formata_grande_int(num: int) -> str:
  '''
    Recebe um valor inteiro e, caso ele seja maior que 1.000, formata para
    melhor visualização
    :param num (int): Número que será formatado.
    :return num_formatado (str): Número formatado.
  '''
  num_formatado = f"{num:,.2f}"
  num_formatado = num_formatado.replace(".00", "")
  num_formatado = num_formatado.replace(",", ".")
  return num_formatado

In [18]:
# 1) Sua solução aqui
# Usa len() para saber o número de instâncias da base

num_vacinas = formata_grande_int(len(df_vacinas_acre))

print(f"Na base de dados foram registradas {num_vacinas} vacinas aplicadas!")

Na base de dados foram registradas 182.451 vacinas aplicadas!

### 3.2 Quantos pacientes foram vacinados? (considere um paciente para cada valor único de paciente_id)

In [19]:
# 2)
'''
Seleciona a coluna paciente_id, que provavelmente contêm dados do paciente que
recbeu a vacina, usa o módulo unique(), para retirar as duplicatas, e o len(),
para saber o número de pacientes
'''
num = formata_grande_int(len(df_vacinas_acre.paciente_id.unique()))

print(f"Foram vacinados {num} pacientes no Acre.")

Foram vacinados 148.319 pacientes no Acre.

### 3.3 Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método .unique().

In [20]:
# 3)
# Seleciona o valor de primeira dose e usa esse valor para selecionar colunas e valores na DataFrame
seleciona_dose = df_vacinas_acre["vacina_descricao_dose"].value_counts().index[0]
filtra_pacientes = df_vacinas_acre['vacina_descricao_dose'] == seleciona_dose

num = len(df_vacinas_acre[filtra_pacientes]['paciente_id'].unique())
num = formata_grande_int(num)

print(f"{num} pacientes tomaram a primeira dose no Acre.")

66.142 pacientes tomaram a primeira dose no Acre.

In [21]:
# 3) solução alternativa
# Seleciona o valor de primeira dose como string e usa esse valor para selecionar colunas e valores na DataFrame

seleciona_dose = '1ª Dose'
filtra_pacientes = df_vacinas_acre['vacina_descricao_dose'] == seleciona_dose

num = len(df_vacinas_acre[filtra_pacientes]['paciente_id'].unique())
num = formata_grande_int(num)

print(f"{num} pacientes tomaram a primeira dose no Acre.")

66.142 pacientes tomaram a primeira dose no Acre.

In [22]:
# 3) solução alternativa
# A maioria dos pacientes tom a primeira dose, por isso a função value_counts já retorna o valor desejado

num = df_vacinas_acre[filtra_pacientes]['vacina_descricao_dose'].value_counts()[0]

num = formata_grande_int(num)

print(f"{num} pacientes tomaram a primeira dose no Acre.")

66.183 pacientes tomaram a primeira dose no Acre.

### 3.4 Quantos pacientes com menos de 18 anos foram vacinados?

In [23]:
# 4)
# Seleciona os pacientes com menos de 18 anos

filtra_pacientes = df_vacinas_acre['paciente_idade'] < 18

# Filtra da DataFrame esses pacientes e recupera apenas os pacientes, sem duplicatas
num = len(df_vacinas_acre[filtra_pacientes]['paciente_id'].unique())
num = formata_grande_int(num)

print(f"{num} pacientes com menos de 18 anos tomaram vacina no Acre.")

24.604 pacientes com menos de 18 anos tomaram vacina no Acre.

### 3.5 Quantos estabelecimentos aplicaram vacina no Acre?

In [24]:
# 5)
# Filtra da DataFrame os estabelecimentos, sem duplicatas

num = len(df_vacinas_acre['estabelecimento_valor'].unique())
num = formata_grande_int(num)

print(f"{num} estabelecimentos aplicaram vacinas no Acre.")

177 estabelecimentos aplicaram vacinas no Acre.

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vacinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [25]:
# 1)
# Filtra os pacientes com menos de 18 anos
filtra_pacientes = df_vacinas_acre['paciente_idade'] < 18

# Busca os estabelecimentos que administraram vacinas nesses pacientes
df_vacinas_acre_estabelecimento = df_vacinas_acre[filtra_pacientes]['estabelecimento_valor']

# Conta quantas vacinas foram aplicadas por estabelecimentos, instanciando uma DataFrame
df_vacinas_acre_estabelecimento = pd.DataFrame(df_vacinas_acre_estabelecimento.value_counts())

# Obtem uma coluna com os estabelecimentos, sem index
df_vacinas_acre_estabelecimento = df_vacinas_acre_estabelecimento.reset_index()

# Nemomeia as colunas
df_vacinas_acre_estabelecimento.columns = ['estabelecimento_valor','num_doses']
df_vacinas_acre_estabelecimento.head()

   estabelecimento_valor  num_doses
0                6917291      23346
1                2002876        406
2                2000660        310
3                2001101        150
4                2002922        146

### 4.1 Crie uma cópia do DataFrame original, contendo somente os registros de vacinas realizadas a menores de 18 anos.

In [26]:
# Instancia uma cópia da DataFrame original, para pacientes com menos de 18 anos
df_vacinas_acre_pacientes = df_vacinas_acre[filtra_pacientes].copy()
df_vacinas_acre_pacientes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27382 entries, 6 to 375501
Data columns (total 32 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   document_id                               27382 non-null  object
 1   paciente_id                               27382 non-null  object
 2   paciente_idade                            27382 non-null  int64
 3   paciente_dataNascimento                   27382 non-null  object
 4   paciente_enumSexoBiologico                27382 non-null  object
 5   paciente_racaCor_codigo                   27382 non-null  int64
 6   paciente_racaCor_valor                    27382 non-null  object
 7   paciente_endereco_coIbgeMunicipio         27382 non-null  object
 8   paciente_endereco_coPais                  27382 non-null  object
 9   paciente_endereco_nmMunicipio             27382 non-null  object
 10  paciente_endereco_nmPais                  27382 non-null  object
 11  paciente_endereco_uf                      27382 non-null  object
 12  paciente_endereco_cep                     23172 non-null  object
 13  paciente_nacionalidade_enumNacionalidade  27379 non-null  object
 14  estabelecimento_valor                     27382 non-null  int64
 15  estabelecimento_razaoSocial               27382 non-null  object
 16  estalecimento_noFantasia                  27382 non-null  object
 17  estabelecimento_municipio_codigo          27382 non-null  int64
 18  estabelecimento_municipio_nome            27382 non-null  object
 19  estabelecimento_uf                        27382 non-null  object
 20  vacina_grupoAtendimento_codigo            27382 non-null  int64
 21  vacina_grupoAtendimento_nome              26920 non-null  object
 22  vacina_categoria_codigo                   19033 non-null  float64
 23  vacina_categoria_nome                     19033 non-null  object
 24  vacina_lote                               27382 non-null  object
 25  vacina_fabricante_nome                    27382 non-null  object
 26  vacina_fabricante_referencia              27362 non-null  object
 27  vacina_dataAplicacao                      27382 non-null  object
 28  vacina_descricao_dose                     27382 non-null  object
 29  vacina_codigo                             27382 non-null  int64
 30  vacina_nome                               27380 non-null  object
 31  sistema_origem                            27379 non-null  object
dtypes: float64(1), int64(6), object(25)
memory usage: 6.9+ MB

### 4.2 Crie uma lista das colunas desse DataFrame com o atributo de DataFrame .columns()

In [27]:
# 2)
# Instancia uma lista com os nomes das colunas da DataFrame

lista_colunas = df_vacinas_acre_pacientes.columns
lista_colunas

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

### 4.3 Nesse DataFrame faça uma contagem do campo vacina_categoria_nome.

In [28]:
# 3)
# Conta as vacinas aplicadas por categoria.

df_vacinas_acre_pacientes['vacina_categoria_nome'].value_counts()

Faixa Etária                        18733
Outros                                151
Povos e Comunidades Tradicionais       44
Povos Indígenas                        43
Comorbidades                           23
População Privada de Liberdade         18
Gestantes                              13
Trabalhadores de Saúde                  6
Pessoas Institucionalizadas             2
Name: vacina_categoria_nome, dtype: int64

### 4.4 A partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.

In [29]:
# 4)
# Instancia uma lista com as colunas referêntes aos estabelecimentos

colunas_estabelecimentos = [col for col in lista_colunas if 'estabelecimento_' in col]
colunas_estabelecimentos

['estabelecimento_valor',
 'estabelecimento_razaoSocial',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf']

### 4.5 Usando o método .loc, selecione somente essas variáveis

In [30]:
# 5)
# Seleciona apenas os dados dos estabelecimentos

df_vacinas_acre_pacientes_estabelecimento = df_vacinas_acre_pacientes.loc[:, colunas_estabelecimentos]
df_vacinas_acre_pacientes_estabelecimento.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27382 entries, 6 to 375501
Data columns (total 5 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   estabelecimento_valor             27382 non-null  int64
 1   estabelecimento_razaoSocial       27382 non-null  object
 2   estabelecimento_municipio_codigo  27382 non-null  int64
 3   estabelecimento_municipio_nome    27382 non-null  object
 4   estabelecimento_uf                27382 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.3+ MB

### 4.6 Aplique o método .drop_duplicates e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [31]:
# 6)
# Retira as duplicadas dos dados dos estebelecimentos

df_vacinas_acre_pacientes_estabelecimento_drop_duplicates = df_vacinas_acre_pacientes_estabelecimento.drop_duplicates()
df_vacinas_acre_pacientes_estabelecimento_drop_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 139 entries, 6 to 369540
Data columns (total 5 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   estabelecimento_valor             139 non-null    int64
 1   estabelecimento_razaoSocial       139 non-null    object
 2   estabelecimento_municipio_codigo  139 non-null    int64
 3   estabelecimento_municipio_nome    139 non-null    object
 4   estabelecimento_uf                139 non-null    object
dtypes: int64(2), object(3)
memory usage: 6.5+ KB

In [32]:
# Junta os dados de número de vacinas aplicadas por estabelecimentos, com os dados dos estabelecimentos.

df_concat = df_vacinas_acre_estabelecimento.merge(df_vacinas_acre_pacientes_estabelecimento_drop_duplicates)
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   estabelecimento_valor             139 non-null    int64
 1   num_doses                         139 non-null    int64
 2   estabelecimento_razaoSocial       139 non-null    object
 3   estabelecimento_municipio_codigo  139 non-null    int64
 4   estabelecimento_municipio_nome    139 non-null    object
 5   estabelecimento_uf                139 non-null    object
dtypes: int64(3), object(3)
memory usage: 7.6+ KB